language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: ENV["heroku_api_key"]
  app: viewingpartymikeandaustin
  run: rails db:migrate
  on:
    repo: austin/viewing_party
    branch: main
  skip_cleanup: 'true'
